enum pot_event_type {
  create_v1
  chat_v1
  user_in_v1
  user_leave_v1
  user_kick_v1
  departure_confirm_v1
  accounting_request_v1
  accounting_confirm_v1
  archive_v1
}

table users {
  pk uuid [pk, not null]
  is_deleted boolean [not null]
  name varchar(32) [not null]
  created_at "timestamp with time zone" [not null, default: `now()`]
  updated_at "timestamp with time zone" [not null, default: `now()`]
}

table user_pot_room {
  user_fk uuid [not null]
  pot_room_fk uuid [not null]

  indexes {
    (user_fk, pot_room_fk) [pk]
  }
}

table pot_room {
  pk uuid [pk, not null]
  route_fk uuid [not null]
  is_closed boolean [not null, default: false]
  is_deleted boolean [not null, default: false]
  max_num smallint [not null]
  created_at "timestamp with time zone" [not null, default: `now()`]
  updated_at "timestamp with time zone" [not null, default: `now()`]
  name varchar(64) [not null]
}

table pot_event {
  pot_fk uuid [not null]
  timestamp "timestamp with time zone" [not null]
  type pot_event_type [not null]
  data jsonb [not null]

  indexes {
    (pot_fk, timestamp) [pk]
    (pot_fk, type) [name: 'idx_pot_event_pot_fk_type']
  }
}

table user_alarm_setting {
  pk uuid [pk, not null]
  device_fk uuid [not null]
  any_push boolean [not null, default: true]
  chat_push boolean [not null, default: true]
  marketing_push boolean [not null, default: true]
  pot_in_out_push boolean [not null, default: true]
}

table route {
  pk uuid [pk, not null]
  from_stop smallint [not null]
  to_stop smallint [not null]
  created_at "timestamp with time zone" [not null, default: `now()`]
  updated_at "timestamp with time zone" [not null, default: `now()`]
}

table device {
  pk uuid [pk, not null]
  user_fk uuid [not null]
  fcm_token varchar(64) [not null]
  os varchar(4) [not null]
  version varchar(8) [not null]
  created_at "timestamp with time zone" [not null, default: `now()`]
  updated_at "timestamp with time zone" [not null, default: `now()`]
}

table bank {
  pk uuid [pk, not null]
  bank_short_name varchar(64) [not null]
  bank_full_name varchar(64) [not null]
  logo text [not null]
}

table user_bank {
  user_fk uuid [not null]
  bank_fk uuid [not null]
  account varchar(64) [not null]

  indexes {
    (user_fk, bank_fk) [pk]
  }
}

ref: user_pot_room.user_fk > users.pk

ref: user_pot_room.pot_room_fk > pot_room.pk

ref: pot_room.route_fk > route.pk

ref: pot_event.pot_fk > pot_room.pk

ref: user_alarm_setting.device_fk > device.pk

ref: device.user_fk > users.pk

ref: user_bank.user_fk > users.pk

ref: user_bank.bank_fk > bank.pk